update attachments xmpl
cap-js/incidents-app pull request #55
Opened 2024-03-29 05:51 UTC by muskansethi1

Removed images implementation and updated script as package is released

2024-04-02 07:19 UTC, RamIndia requested changes

2024-04-02 07:19 UTC, RamIndia commented on xmpls/attachments/db/init.js
>  module.exports = async function () {
Remove init js

2024-04-02 07:19 UTC, RamIndia commented on xmpls/attachments/db/attachments.cds
this should be under xmpl itself

2024-04-06 06:55 UTC, DanSchlachter approved these changes
Thank you!

2024-04-09 09:44 UTC, DanSchlachter approved these changes

2024-04-10 06:11 UTC, merged